// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7sqs6PbQaCRIdorMp4bmUQSxh2loRgKs',
    appId: '1:784726722134:web:10c440576ee8a9e1d49df7',
    messagingSenderId: '784726722134',
    projectId: 'whatsapp-4b0bb',
    authDomain: 'whatsapp-4b0bb.firebaseapp.com',
    storageBucket: 'whatsapp-4b0bb.appspot.com',
    measurementId: 'G-1YBSJ4NK68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd9Dx1LPrBGNkJmtpyQTXG0hUSLnq1gRw',
    appId: '1:784726722134:android:9179789f2aaa8822d49df7',
    messagingSenderId: '784726722134',
    projectId: 'whatsapp-4b0bb',
    storageBucket: 'whatsapp-4b0bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYCJB_3kNi3DWE42TVIEfRLP0UYZ4bOPY',
    appId: '1:784726722134:ios:b5978e80fc596b0cd49df7',
    messagingSenderId: '784726722134',
    projectId: 'whatsapp-4b0bb',
    storageBucket: 'whatsapp-4b0bb.appspot.com',
    iosClientId: '784726722134-9eqrmfrs19og2ndde95h2r42k5j3peeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYCJB_3kNi3DWE42TVIEfRLP0UYZ4bOPY',
    appId: '1:784726722134:ios:b5978e80fc596b0cd49df7',
    messagingSenderId: '784726722134',
    projectId: 'whatsapp-4b0bb',
    storageBucket: 'whatsapp-4b0bb.appspot.com',
    iosClientId: '784726722134-9eqrmfrs19og2ndde95h2r42k5j3peeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
